<?php
use Transoft\Blog\Block\Bloglist;
?>
<?php /** @var Bloglist $block*/
?>
<?php
$bloglist = $block->getData('bloglist');
$data = $bloglist->getPostCollection();
?>

<?php if ($bloglist->isTypesMatching()): ?>
    <div>
        <h3><?= $block->escapeHtml(__('Latest 5 blogs:')) ?></h3>
        <ul>
            <?php foreach ($data as $value):
                $theme = $value->getTheme();
                $url = $block->escapeUrl($bloglist->getUrlById($value->getBlogId()));
                ?>
                <li><a href="<?= $block->escapeUrl($url) ?>"><?= $block->escapeUrl($theme) ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
