<?php

use Magento\Framework\Exception\NoSuchEntityException;
use Transoft\Blog\Block\SingleBlog;
?>
<?php /** @var SingleBlog $block*/ ?>
<?php
$id = $block->getBlogId();
try {
    $blog = $block->getBlogById($id);
} catch (NoSuchEntityException $e) {
    $block->_logger->warning($e);
}
?>

<div>
    <h3><?= $block->escapeHtml($blog->getTheme()) ?></h3>
    <div>
        <span><strong><?= $block->escapeHtml(__("Content:")) ?></strong></span><br />
        <p><?= $block->escapeHtml($blog->getContent()) ?></p><br />
        <span><strong>Image:</strong></span><br />
        <img src="<?= $block->escapeUrl($blog->getImagePath()) ?>"
             alt="<?= $block->escapeHtmlAttr(__($block->getTheme())) ?>"
             width="300"
             height="300"
        /><br />
        <span><strong>Created at:</strong></span><br />
        <p><?= $block->escapeHtml($blog->getCreationTime()) ?></p>
    </div>
</div>
