<?php
use Transoft\Blog\Block\SingleBlog;
?>
<?php /** @var SingleBlog $block*/ ?>
<?php
$id = $block->getBlogId();
$blog = $block->getBlogById($id);
?>

<div>
    <h3><?= $block->escapeHtml($blog->getTheme()) ?></h3>
    <div>
        <span><strong>Content:</strong></span>
        <p><?= $block->escapeHtml($blog->getContent()) ?></p>
        <span><strong>Image:</strong></span>
        <img src="<?= $block->escapeUrl($blog->getImagePath()) ?>"
             alt="<?= $block->escapeHtmlAttr(__($block->getTheme())) ?>"
             width="300"
             height="300"
        />
        <span><strong>Created at:</strong></span>
        <p><?= $blog->getCreationTime() ?></p>
    </div>
</div>
