<?php
use Transoft\Blog\Block\Bloglist;
?>
<?php /** @var Bloglist $block*/ ?>
<?php
$bloglist = $block->getData('bloglist');
$id = $bloglist->getBlogId();
$blog = $bloglist->getBlogById($id);
?>

<div>
    <h3><?= $block->escapeHtml($blog->getTheme()) ?></h3>
    <div>
        <span><strong>Content:</strong></span>
        <p><?= $block->escapeHtml($blog->getContent()) ?></p>
        <span><strong>Image:</strong></span>
        <img src="<?= $block->escapeUrl($blog->getImagePath()) ?>"
             alt="<?= $block->escapeHtmlAttr(__("Image")) ?>"
             width="<?= $block->escapeHtmlAttr("300") ?>"
             height="<?= $block->escapeHtmlAttr("300") ?>"
        />
        <span><strong>Created at:</strong></span>
        <p><?= $block->escapeHtml($blog->getCreationTime()) ?></p>
    </div>
</div>
