<?php

use Transoft\Blog\Block\SingleBlog;
?>
<?php /** @var SingleBlog $block*/ ?>
<?php
$id = $block->getPostId();
$post = $block->getPostById($id);
?>

<div>
    <h3><?= $block->escapeHtml($post->getTheme()) ?></h3>
    <div>
        <span><strong><?= $block->escapeHtml(__("Content:")) ?></strong></span><br />
        <p><?= $block->escapeHtml($post->getContent()) ?></p><br />
        <span><strong>Image:</strong></span><br />
        <img src="<?= $block->escapeUrl($post->getImagePath()) ?>"
             alt="<?= $block->escapeHtmlAttr(__($block->getTheme())) ?>"
             width="300"
             height="300"
        /><br />
        <span><strong>Created at:</strong></span><br />
        <p><?= $block->escapeHtml($post->getCreationTime()) ?></p>
    </div>
</div>
